import { NextRequest, NextResponse } from 'next/server';

export const runtime = 'edge';

export async function POST(request: NextRequest) {
  try {
    const { nodes, edges, format = 'json', name = 'my-workflow' } = await request.json();

    if (!nodes) {
      return NextResponse.json({ error: 'Workflow nodes required' }, { status: 400 });
    }

    let output = '';
    let mimeType = 'application/json';
    let fileExt = 'json';

    switch (format) {
      case 'json':
        output = JSON.stringify({ name, nodes, edges }, null, 2);
        break;

      case 'yaml':
        output = `name: ${name}\nnodes:\n${nodes.map((n: any) => `  - id: ${n.id}\n    type: ${n.type}\n    label: ${n.data?.label || n.type}`).join('\n')}\nedges:\n${(edges || []).map((e: any) => `  - from: ${e.source}\n    to: ${e.target}`).join('\n')}`;
        break;

      case 'typescript':
        output = `// Auto-generated by TriForce AI\nexport const workflow = {\n  name: "${name}",\n  nodes: ${JSON.stringify(nodes, null, 2).split('\n').join('\n  ')},\n  edges: ${JSON.stringify(edges || [], null, 2)},\n};\n\nexport async function execute(input: any) {\n  let current = input;\n${nodes.filter((n: any) => n.type === 'ai').map((n: any) => `  // ${n.data?.label}\n  // current = await processNode("${n.id}", current);`).join('\n')}\n  return current;\n}`;
        break;

      case 'python':
        output = `# Auto-generated by TriForce AI\nworkflow = {\n    "name": "${name}",\n    "nodes": ${JSON.stringify(nodes)},\n    "edges": ${JSON.stringify(edges || [])},\n}\n\nasync def execute(input_data):\n    current = input_data${nodes.filter((n: any) => n.type === 'ai').map((n: any) => `\n    # ${n.data?.label}\n    # current = await process_node("${n.id}", current)`).join('')}\n    return current`;
        break;

      default:
        output = JSON.stringify({ name, nodes, edges }, null, 2);
    }

    const extMap: Record<string, string> = { json: 'json', yaml: 'yaml', typescript: 'ts', python: 'py' };
    fileExt = extMap[format] || 'json';

    return NextResponse.json({
      success: true,
      format,
      output,
      filename: `${name}.${fileExt}`,
      mimeType,
    });
  } catch (error) {
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Export failed' },
      { status: 500 }
    );
  }
}
