import { NextRequest, NextResponse } from 'next/server';

export const runtime = 'edge';

const PROVIDERS = {
  groq: { baseUrl: 'https://api.groq.com/openai/v1', models: ['llama-3.3-70b-versatile'], envKey: 'GROQ_API_KEY' },
  mistral: { baseUrl: 'https://api.mistral.ai/v1', models: ['mistral-small-latest'], envKey: 'MISTRAL_API_KEY' },
} as const;

async function generatePatch(repoUrl: string, description: string): Promise<{ title: string; body: string; files: Array<{ path: string; content: string }> }> {
  const config = PROVIDERS.groq;
  const apiKey = process.env[config.envKey];
  if (!apiKey) throw new Error('GROQ_API_KEY not configured');

  const prompt = `You are generating a GitHub PR for: ${repoUrl}
Issue description: ${description}

Output ONLY valid JSON:
{
  "title": "fix: <short description>",
  "body": "## Problem\\n<description>\\n\\n## Solution\\n<fix details>",
  "files": [{"path": "<file>", "content": "<fixed code>"}]
}`;

  const response = await fetch(`${config.baseUrl}/chat/completions`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: config.models[0],
      messages: [
        { role: 'system', content: 'You output ONLY valid JSON, no markdown fences.' },
        { role: 'user', content: prompt },
      ],
      temperature: 0.5,
      max_tokens: 4096,
    }),
  });

  if (!response.ok) throw new Error(`Provider error: ${response.status}`);
  const data = await response.json();
  const text = data.choices?.[0]?.message?.content || '';
  const cleaned = text.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();

  return JSON.parse(cleaned);
}

export async function POST(request: NextRequest) {
  try {
    const { repoUrl, description, token } = await request.json();

    if (!repoUrl || !token) {
      return NextResponse.json(
        { error: 'Repository URL and GitHub token are required' },
        { status: 400 }
      );
    }

    const match = repoUrl.match(/github\.com\/([^/]+)\/([^/]+)/);
    if (!match) {
      return NextResponse.json({ error: 'Invalid GitHub URL' }, { status: 400 });
    }

    const [, owner, repo] = match;

    const patch = await generatePatch(repoUrl, description || 'General improvements');

    const headers: Record<string, string> = {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json',
    };

    const mainRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/branches/main`, { headers });
    if (!mainRes.ok) {
      return NextResponse.json({ error: 'Could not access repository. Check token permissions.' }, { status: 403 });
    }
    const mainData = await mainRes.json();
    const baseSha = mainData.commit.sha;

    const branchName = `triforce-fix-${Date.now()}`;

    await fetch(`https://api.github.com/repos/${owner}/${repo}/git/refs`, {
      method: 'POST',
      headers,
      body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha: baseSha }),
    });

    for (const file of patch.files || []) {
      await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${file.path}`, {
        method: 'PUT',
        headers,
        body: JSON.stringify({
          message: `fix: update ${file.path}`,
          content: btoa(unescape(encodeURIComponent(file.content))),
          branch: branchName,
        }),
      });
    }

    const prRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls`, {
      method: 'POST',
      headers,
      body: JSON.stringify({
        title: patch.title,
        body: patch.body + '\n\n---\n🤖 Generated by [TriForce AI](https://triforce-ai.pages.dev)',
        head: branchName,
        base: 'main',
      }),
    });

    if (!prRes.ok) {
      const errBody = await prRes.text();
      return NextResponse.json({ error: `PR creation failed: ${errBody}` }, { status: 500 });
    }

    const pr = await prRes.json();

    return NextResponse.json({
      success: true,
      prUrl: pr.html_url,
      prNumber: pr.number,
      branch: branchName,
      filesChanged: (patch.files || []).length,
    });
  } catch (error) {
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'PR creation failed' },
      { status: 500 }
    );
  }
}
